version: '3.8'

services:
  postgresql:
    image: postgres:alpine3.14
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres-users
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-users
    ports:
      - '6379-6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
